### ISSUE TITLE
quote of the day too big and cannot wrap

### ISSUE THREAD

**Issue by yuz876** [cse110-sp21-group26/cse110-sp21-group26#42]
could make the text size smaller maybe?

could make the words wrapped when it is wider than the box? like "dreams" in the. screenshot.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/36283914/121617975-d5365400-ca1a-11eb-94af-258b7ccd22b7.png">

**Comment by yuz876** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/36283914/121618413-8f2dc000-ca1b-11eb-8ff2-b758f7ad38e8.png">

**Comment by karansidz** [comment]
Fixed quote too big by modifying size
